In [22]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [23]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [24]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [26]:
rewards_all_episodes = []

for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode):
        # Exploration-explotation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if(exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        # Take new action
        new_state, reward, done, truncated, info = env.step(action)
        # Update Q - table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state
        state = new_state
        # Add new reward
        rewards_current_episode += reward
        if done == True:
            break
        
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    # Add currect episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000

print("****** Average reward per thousand ep ****** \n")
for r in rewards_per_thousand_episodes:
    print(count, ": " , str(sum(r / 1000)))
    count += 1000
    

/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


****** Average reward per thousand ep ****** 

1000 :  0.057000000000000044
2000 :  0.20600000000000016
3000 :  0.3710000000000003
4000 :  0.5740000000000004
5000 :  0.6410000000000005
6000 :  0.6450000000000005
7000 :  0.6560000000000005
8000 :  0.6850000000000005
9000 :  0.6480000000000005
10000 :  0.6820000000000005


In [27]:
print("\n\n ****** Q-Table ******* \n")
print(q_table)



 ****** Q-Table ******* 

[[0.58399704 0.50404291 0.49449794 0.49422933]
 [0.32895486 0.34317757 0.29395474 0.49687679]
 [0.40974704 0.26981931 0.24775736 0.28190471]
 [0.1875172  0.05725844 0.03850076 0.05216075]
 [0.59918591 0.37392714 0.2365721  0.31268786]
 [0.         0.         0.         0.        ]
 [0.17502947 0.17667759 0.34788756 0.09382875]
 [0.         0.         0.         0.        ]
 [0.46081912 0.47664669 0.44228857 0.64999727]
 [0.38955328 0.70042729 0.56511185 0.53444732]
 [0.69622822 0.40863156 0.3979801  0.28958977]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45948987 0.48167025 0.78313729 0.51592712]
 [0.67586252 0.89562685 0.74512096 0.71771841]
 [0.         0.         0.         0.        ]]


In [29]:
# Watch them play
for episode in range(3):
    # initialize new episode params
    state = env.reset()[0]
    done = False
    print("****EPISODE", episode + 1, "*******\n\n\n\n")
    time.sleep(1) 
    for step in range(max_steps_per_episode):
        # Show current state of environment on screen
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)
        # Choose action with highest Q-value for current statyte
        action = np.argmax(q_table[state, :])
        new_state, reward, done, truncated, info = env.step(action)
        # Take new action
    
        if done:
            clear_output(wait = True)
            print(env.render())
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
                # Agent reached the goan and won episode
            else:
                # Agent stepped in a hole and lost episode
                print("**** You fell through a hole ****")
                time.sleep(3)
                clear_output(wait=True)
            break
        # Set new state
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG

****You reached the goal!****
